#!/bin/bash
set -eo pipefail

function main {
  local cmd="$@"
  [ -z "$cmd" ] && cmd=nginx

  ulimit -n 65535
  : ${TRANSMISSION_HOST:=$TRANSMISSION_PORT_9091_TCP_ADDR}

  for conf in /etc/nginx/nginx.conf.tpl $(ls /etc/nginx/conf.d/*.tpl)
  do
    envtpl "$conf"
  done

  exec "$cmd"
}

main "$@"
exit 0